Revert "conf: Change the WKS_FILE setting to more weaker level"
WKS_FILE variable is set by image_types_wic.bbclass by using "?=".
Thus, with this patch, default variable on
iamge recipe(${IMAGE_BASENAME}.${MACHINE}.wks" is used instead of variable in
machine/sparrow-hawk.conf.
We can not build image without overriding WKS_FILE in recipe or local.conf.

Error log:
```
ERROR: core-image-minimal-1.0-r0 do_image_wic: No kickstart files from
WKS_FILES were found: core-image-minimal.sparrow-hawk.wks
core-image-minimal.wks. Please set WKS_FILE or WKS_FILES appropriately.
ERROR: core-image-minimal-1.0-r0 do_image_wic:
ExecutionError('/home/runner/work/meta-sparrow-hawk/meta-sparrow-hawk/build/build-sparrow-hawk/tmp/work/sparrow_hawk-poky-linux/core-image-minimal/1.0/temp/run.do_image_wic.2856821',
1, None, None)
ERROR: Logfile of failure stored in:
/home/runner/work/meta-sparrow-hawk/meta-sparrow-hawk/build/build-sparrow-hawk/tmp/work/sparrow_hawk-poky-linux/core-image-minimal/1.0/temp/log.do_image_wic.2856821
NOTE: recipe core-image-minimal-1.0-r0: task do_image_wic: Failed
```

This reverts commit c793097fbf5e252596f4ca0484d4e6bd9dab1060.

Signed-off-by: Yuya Hamamachi <yuya.hamamachi.sx@renesas.com>